# Generated by Django 5.2.1 on 2025-06-08 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0004_alter_booking_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={},
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='created_at',
            new_name='booking_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='updated_at',
        ),
    ]
